# Generated by Django 2.2.3 on 2020-02-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_auto_20200227_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='RATING',
            field=models.IntegerField(null=True),
        ),
    ]
