# Generated by Django 2.2.3 on 2020-02-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_auto_20200227_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='RATING',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
