# Generated by Django 2.2.3 on 2020-02-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_auto_20200227_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='DATE',
            field=models.DateField(null=True),
        ),
    ]
