# Generated by Django 2.2.3 on 2020-02-28 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0011_auto_20200227_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ARTIST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Artist')),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('UPLOADED_IMAGE', models.ImageField(upload_to='artist_images')),
                ('ARTIST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Artist')),
            ],
        ),
    ]
