# Generated by Django 2.2.3 on 2020-02-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0014_auto_20200229_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='PASSWORD',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='PASSWORD',
            new_name='password',
        ),
        migrations.AddField(
            model_name='artist',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
