# Generated by Django 2.2.3 on 2020-03-01 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0016_auto_20200301_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='password',
            new_name='PASSWORD',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='password',
            new_name='PASSWORD',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_login',
        ),
    ]
