# Generated by Django 2.2.3 on 2020-02-27 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ARTIST_USERNAME', models.CharField(max_length=30, unique=True)),
                ('PASSWORD', models.CharField(max_length=30)),
                ('ADDRESS', models.CharField(max_length=100)),
                ('RATING', models.IntegerField(blank=True)),
                ('TOTAL_REVIEWS', models.IntegerField(default=0)),
                ('PROFILE_PICTURE', models.ImageField(blank=True, upload_to='profile_images')),
                ('FULL_NAME', models.CharField(max_length=40)),
                ('CONTACT_DETAILS', models.CharField(max_length=80, unique=True)),
                ('STYLE', models.CharField(choices=[(1, 'Nature'), (2, 'Cartoon'), (3, 'Abstract'), (4, 'Geometric'), (5, 'Realism'), (6, 'Tribal'), (7, 'Sleave'), (8, 'Writing'), (9, 'Non-english Writing'), (10, 'Other')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Artists',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(max_length=30, unique=True)),
                ('PASSWORD', models.CharField(max_length=30)),
                ('PROFILE_PICTURE', models.ImageField(blank=True, upload_to='profile_images')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('PICTURE', models.ImageField(upload_to='review_images')),
                ('TITLE', models.CharField(max_length=50)),
                ('DESCRIPTION', models.URLField()),
                ('RATING', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('DATE', models.DateField()),
                ('ARTIST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Artist')),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='page',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
