# Generated by Django 2.2.3 on 2020-02-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0009_auto_20200227_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='slug',
        ),
        migrations.AlterField(
            model_name='review',
            name='ID',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
