# Generated by Django 2.2.3 on 2020-02-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0010_auto_20200227_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='CONTACT_DETAILS',
            field=models.CharField(max_length=80),
        ),
    ]
