# Generated by Django 2.2.3 on 2020-02-29 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0013_auto_20200228_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'verbose_name_plural': 'Pictures'},
        ),
        migrations.AlterModelOptions(
            name='saves',
            options={'verbose_name_plural': 'Saves'},
        ),
    ]
