# Generated by Django 2.2.3 on 2020-03-03 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ARTIST_USERNAME', models.CharField(max_length=30, unique=True)),
                ('PASSWORD', models.CharField(max_length=10000)),
                ('ADDRESS', models.CharField(max_length=100)),
                ('RATING', models.IntegerField(null=True)),
                ('TOTAL_REVIEWS', models.IntegerField(default=0)),
                ('PROFILE_PICTURE', models.ImageField(blank=True, upload_to='profile_images')),
                ('FULL_NAME', models.CharField(max_length=40)),
                ('CONTACT_DETAILS', models.CharField(max_length=80)),
                ('STYLE_1', models.CharField(choices=[(1, 'Nature'), (2, 'Cartoon'), (3, 'Abstract'), (4, 'Geometric'), (5, 'Realism'), (6, 'Tribal'), (7, 'Sleave'), (8, 'Writing'), (9, 'Non-english Writing'), (10, 'Other')], max_length=20)),
                ('STYLE_2', models.CharField(blank=True, choices=[(1, 'Nature'), (2, 'Cartoon'), (3, 'Abstract'), (4, 'Geometric'), (5, 'Realism'), (6, 'Tribal'), (7, 'Sleave'), (8, 'Writing'), (9, 'Non-english Writing'), (10, 'Other')], max_length=20)),
                ('STYLE_3', models.CharField(blank=True, choices=[(1, 'Nature'), (2, 'Cartoon'), (3, 'Abstract'), (4, 'Geometric'), (5, 'Realism'), (6, 'Tribal'), (7, 'Sleave'), (8, 'Writing'), (9, 'Non-english Writing'), (10, 'Other')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Artists',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(max_length=30, unique=True)),
                ('PASSWORD', models.CharField(max_length=10000)),
                ('PROFILE_PICTURE', models.ImageField(blank=True, upload_to='profile_images')),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Saves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ARTIST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INKLined_app.Artist')),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INKLined_app.Customer')),
            ],
            options={
                'verbose_name_plural': 'Saves',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('PICTURE', models.ImageField(upload_to='review_images')),
                ('TITLE', models.CharField(max_length=50)),
                ('DESCRIPTION', models.URLField()),
                ('RATING', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('DATE', models.DateField(null=True)),
                ('ARTIST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INKLined_app.Artist')),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INKLined_app.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('UPLOADED_IMAGE', models.ImageField(upload_to='artist_images')),
                ('ARTIST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INKLined_app.Artist')),
            ],
            options={
                'verbose_name_plural': 'Pictures',
            },
        ),
    ]
