# Generated by Django 2.2.3 on 2020-03-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INKLined_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='RATING',
            field=models.IntegerField(default=None),
        ),
    ]
