# Generated by Django 2.2.3 on 2020-03-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INKLined_app', '0002_auto_20200330_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='STYLE_1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='artist',
            name='STYLE_2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='artist',
            name='STYLE_3',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
