# Generated by Django 2.2.3 on 2020-04-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INKLined_app', '0003_auto_20200330_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='RATING',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
